config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'home#index'
  get 'home/about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user, :optional => true
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use : null_session insted.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
    protected
   
     def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
     end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end 
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index, :show]
  before_action :current_user, only: [:edit, :update, :destroy]


  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.update(user_id:current_user.id)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image ,:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container">
<%= link_to 'Pinterested', root_path, class: 'navbar-brand'%>
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="nav navbar-nav navbar-right ">

    <li><%= link_to 'Home', root_path %></li>
    <li> <%= link_to 'About Us', home_about_path %></li>

    <% if user_signed_in? %>
    <li><%= link_to 'New Pins' , new_pin_path %></li>
    <li><%= link_to 'List Pins' , pins_path %></li>
    <li> <%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
    <li><%= link_to 'edit profile',edit_user_registration_path %>
    <% else %>
    <li> <%= link_to 'login', new_user_session_path %></li>
    <li><%= link_to 'join' , new_user_registration_path %> </li>

    <%end %>
   
    
    </div>
  </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> about Me!<h1>
<p>My name is khaoula and I'm building a Pintersted clone website<p>

app/views/home/index.html.erb
<div class="jumbotron center">
<h1> Welcome to my printerested! </h1>
<p> Pretty cool, don't you thinks? </p>

<% if user_signed_in? %>
    <%= link_to 'logout', destroy_user_session_path, method: :delete , class: 'btn btn-primary' %>
    <%= link_to 'edit profile',edit_user_registration_path ,class: 'btn btn-default' %>
    <%= link_to 'List Pins' , pins_path , class: 'btn btn-default' %>


<% else %>

  <%= link_to 'login', new_user_session_path, class: 'btn btn-default' %>
  <%= link_to 'join' , new_user_registration_path, class: 'btn btn-primary' %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterested</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'home/header' %>
<div class="container">
 <% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert-info") %>
<% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="from_group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="from_group">
  <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control' %>
    </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'from-control'  %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading"><h1>Editing Pin</h1></div>

    <div class="panel-body">

        <%= render 'form', pin: @pin %>
    </div>

        <div class="panel-footer"><%= link_to 'Show', @pin %> | <%= link_to 'Back', pins_path %></div>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">

<% @pins.each do |pin| %>

  <div class="box">
      <% if pin.image.attached? %>
        <image src="<%=(url_for(pin.image))%>" , width= '300px' , height = '300px'></br>
      <% end %>
      <b><%= pin.description %></b><br/>
      <%= pin.user.email if pin.user  %><br/>
      <%= link_to 'Show', pin %>
      <% if pin.user == current_user %>
         <%= link_to 'Edit', edit_pin_path(pin) %>
         <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>     
      </br> 
  </div>
<% end %>
</div> 

app/views/pins/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading"><h1>New Pin</h1></div>

    <div class="panel-body">
        <%= render 'form', pin: @pin %>
    </div>

    <div class="panel-footer"><%= link_to 'Back', pins_path %></div>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
       <div class="panel-heading center">
          <% if @pin.image.attached? %>
            <image src="<%=(url_for(@pin.image))%>" , width= '300px' , height = '300px'>
          <% end %></div>
          <div class="panel-body">

          <strong>Description:</strong>
          <%= @pin.description %></br>
          <strong>User:</strong><%= @pin.user.name if @pin.user %><br/>
           <% if @pin.user != current_user %>
             <%= link_to 'Edit', edit_pin_path(@pin) %> |
           <% end %>
           <%= link_to 'Back', pins_path %>
        </div>
    </div>
  </div>
</div>